import fs from "node:fs";
import path from "node:path";

export function profileFixture() {
  const command = (instructions, evidenceRequired = false) => ({
    mode: "unresolved",
    command: "",
    args: [],
    instructions,
    evidenceRequired
  });
  return {
    schemaVersion: 2,
    project: { id: "fixture", displayName: "Fixture Project" },
    targetRepository: {
      localRelativePath: "../project",
      runtimeRelativePath: "../.ai-runtime",
      allowedRemotes: ["git@github.com:example/project.git"],
      defaultBranch: "main"
    },
    dataPolicy: {
      lane: "amber",
      allowSourceCode: true,
      allowTestData: "synthetic_only",
      deny: ["secrets", "production_data", "personal_data", "project_credentials"]
    },
    ai: {
      defaultTool: "codex",
      codex: { model: "" },
      claude: { model: "" },
      mcpAllowlist: []
    },
    projectCommands: {
      install: command("Determine the approved dependency setup procedure."),
      format: command("Determine the formatting procedure."),
      lint: command("Determine the lint procedure."),
      typecheck: command("Determine the type-check procedure."),
      testTargeted: command("Determine the targeted test procedure.", true),
      testFull: command("Determine the full test procedure.", true),
      build: command("Determine the build procedure.", true)
    },
    humanGates: [
      "architecture_change",
      "new_dependency",
      "destructive_command",
      "commit",
      "push",
      "merge",
      "deployment"
    ]
  };
}

export function permissionsFixture() {
  return {
    policyVersion: 2,
    native: {
      filesystemMode: "workspace-write",
      networkForGeneratedCommands: false,
      approvalMode: "on-request",
      protectedProjectPaths: [".git/**", "**/.git/**", ".github/**", "**/.github/**", ".env", "**/.env", ".env.*", "**/.env.*", "secrets/**", "**/secrets/**"],
      requireHumanConfirmation: ["install_dependency", "commit", "push", "network"],
      deny: ["merge", "deploy", "access_production", "read_user_home_secrets"]
    },
    docker: { projectMount: "read-write" }
  };
}

export function forbiddenArtifactsFixture() {
  return {
    schemaVersion: 1,
    denyPaths: ["AGENTS.md", "**/AGENTS.md", "CLAUDE.md", "**/CLAUDE.md", ".claude/**", "**/.claude/**", ".codex/**", "**/.codex/**", "*.prompt.md", "**/*.prompt.md", ".gitmodules", "**/.gitmodules"],
    denyCommitPatterns: ["Generated by AI", "Generated with (Claude|Codex|ChatGPT)"],
    allowPaths: []
  };
}

export function skillPolicyFixture() {
  return {
    schemaVersion: 1,
    mode: "human-reviewed",
    requireSanitizedFailureRecord: true,
    requireBehavioralEval: true,
    requireAdjacentRegression: true,
    minimumProjectArchetypesForUniversalSkillChange: 2,
    allowAutonomousSkillMutation: false,
    allowAutonomousMerge: false,
    learningData: {
      allow: ["synthetic_cases", "sufficiently_anonymized_failure_patterns", "sanitized_behavioral_scores"],
      deny: ["project_source_code", "raw_prompts_or_transcripts", "secrets", "production_data", "personal_data"]
    }
  };
}

export function writeFixtureConfiguration(aiRoot) {
  const entries = {
    "profile.json": profileFixture(),
    "permissions.json": permissionsFixture(),
    "forbidden-artifacts.json": forbiddenArtifactsFixture(),
    "skill-improvement-policy.json": skillPolicyFixture()
  };
  for (const [name, value] of Object.entries(entries)) {
    fs.writeFileSync(path.join(aiRoot, "project", name), `${JSON.stringify(value, null, 2)}\n`);
  }
}
