import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { writeFixtureConfiguration } from "./fixtures/configuration.mjs";

const sourceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function exec(command, args, cwd) {
  return spawnSync(command, args, { cwd, encoding: "utf8" });
}

function configureFixture(base) {
  const aiRoot = path.join(base, "ai");
  const projectRoot = path.join(base, "project");
  fs.cpSync(sourceRoot, aiRoot, { recursive: true });
  writeFixtureConfiguration(aiRoot);
  fs.mkdirSync(projectRoot);
  assert.equal(exec("git", ["init", "-b", "main"], projectRoot).status, 0);
  exec("git", ["config", "user.email", "aiw-test@example.invalid"], projectRoot);
  exec("git", ["config", "user.name", "AIW Test"], projectRoot);
  fs.writeFileSync(path.join(projectRoot, "README.md"), "fixture\n");
  exec("git", ["add", "README.md"], projectRoot);
  assert.equal(exec("git", ["commit", "-m", "Initial fixture"], projectRoot).status, 0);
  exec("git", ["remote", "add", "origin", "git@github.com:example/project.git"], projectRoot);

  const profilePath = path.join(aiRoot, "project", "profile.json");
  const profile = JSON.parse(fs.readFileSync(profilePath, "utf8"));
  profile.projectCommands.lint = {
    mode: "agent",
    command: "git",
    args: ["status", "--short"],
    instructions: "Inspect worktree status without mutation.",
    evidenceRequired: true
  };
  profile.projectCommands.build = {
    mode: "manual",
    command: "",
    args: [],
    instructions: "A human performs the approved build.",
    evidenceRequired: true
  };
  fs.writeFileSync(profilePath, `${JSON.stringify(profile, null, 2)}\n`);
  return { aiRoot, projectRoot };
}

test("launcher executes configured argv, records evidence, and blocks protected/artifact text", (t) => {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), "aiw-integration-"));
  t.after(() => fs.rmSync(base, { recursive: true, force: true }));
  const { aiRoot, projectRoot } = configureFixture(base);
  const launcher = path.join(aiRoot, "bin", "aiw.mjs");

  const initial = exec(process.execPath, [launcher, "verify"], aiRoot);
  assert.equal(initial.status, 0, initial.stderr);

  const check = exec(process.execPath, [launcher, "check", "lint", "--task", "FIX-1"], aiRoot);
  assert.equal(check.status, 0, check.stderr);
  assert.ok(fs.existsSync(path.join(base, ".ai-runtime", "evidence", "FIX-1", "lint.json")));

  const manual = exec(process.execPath, [launcher, "check", "build", "--task", "FIX-1"], aiRoot);
  assert.equal(manual.status, 3);
  assert.match(manual.stdout, /MANUAL build/);
  const evidence = exec(process.execPath, [launcher, "evidence", "build", "--task", "FIX-1", "--status", "passed", "--note", "Approved manual build passed"], aiRoot);
  assert.equal(evidence.status, 0, evidence.stderr);
  assert.ok(fs.existsSync(path.join(base, ".ai-runtime", "evidence", "FIX-1", "build.json")));

  fs.mkdirSync(path.join(projectRoot, ".github"));
  fs.writeFileSync(path.join(projectRoot, ".github", "workflow.yml"), "name: test\n");
  const protectedResult = exec(process.execPath, [launcher, "verify"], aiRoot);
  assert.equal(protectedResult.status, 2);
  assert.match(`${protectedResult.stdout}${protectedResult.stderr}`, /protected by \.github\/\*\*/);
  fs.rmSync(path.join(projectRoot, ".github"), { recursive: true });

  fs.writeFileSync(path.join(projectRoot, "note.txt"), "Generated by AI\n");
  const textResult = exec(process.execPath, [launcher, "verify"], aiRoot);
  assert.equal(textResult.status, 2);
  assert.match(`${textResult.stdout}${textResult.stderr}`, /Forbidden text patterns/);
  fs.rmSync(path.join(projectRoot, "note.txt"));

  fs.symlinkSync(path.join(base, "outside.txt"), path.join(projectRoot, "outside-link.txt"));
  const symlinkResult = exec(process.execPath, [launcher, "verify"], aiRoot);
  assert.equal(symlinkResult.status, 2);
  assert.match(`${symlinkResult.stdout}${symlinkResult.stderr}`, /untracked symbolic link requires review/);
});

test("red data lane blocks an agent session before tool launch", (t) => {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), "aiw-data-policy-"));
  t.after(() => fs.rmSync(base, { recursive: true, force: true }));
  const { aiRoot } = configureFixture(base);
  const profilePath = path.join(aiRoot, "project", "profile.json");
  const profile = JSON.parse(fs.readFileSync(profilePath, "utf8"));
  profile.dataPolicy.lane = "red";
  fs.writeFileSync(profilePath, `${JSON.stringify(profile, null, 2)}\n`);
  const result = exec(process.execPath, [path.join(aiRoot, "bin", "aiw.mjs"), "start", "--tool", "codex", "--task", "FIX-2"], aiRoot);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /Project source access is disabled by dataPolicy/);
});

test("configuration tests remain stable after project values are customized", (t) => {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), "aiw-custom-profile-"));
  t.after(() => fs.rmSync(base, { recursive: true, force: true }));
  const aiRoot = path.join(base, "ai");
  fs.cpSync(sourceRoot, aiRoot, { recursive: true });
  const profilePath = path.join(aiRoot, "project", "profile.json");
  const profile = JSON.parse(fs.readFileSync(profilePath, "utf8"));
  profile.project = { id: "configured-project", displayName: "Configured Project" };
  profile.targetRepository.defaultBranch = "master";
  profile.targetRepository.allowedRemotes = ["git@gitlab.com:example/configured-project.git"];
  for (const entry of Object.values(profile.projectCommands)) {
    entry.mode = "manual";
    entry.command = "";
    entry.args = [];
    entry.instructions = "A human performs this project-specific operation.";
  }
  fs.writeFileSync(profilePath, `${JSON.stringify(profile, null, 2)}\n`);

  const result = exec(process.execPath, ["--test", "tests/config.test.mjs"], aiRoot);
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
});
